/**
 * Two-sentence descriptions for each lesson (what it teaches). 200 lessons.
 */
export const LESSON_DESCRIPTIONS: Record<string, string> = {
  "1.1.1": "Understand what money is, how it works as a medium of exchange, and why it has value. Learn how currency differs from barter and how modern money fits into daily life.",
  "1.1.2": "Distinguish between needs (essentials for living) and wants (things we desire). Apply this lens to spending choices so you can prioritize and cut waste.",
  "1.1.3": "See how impulse buys happen and why they hurt your finances. Build simple habits and pauses so you can decide with your head, not your emotions.",
  "1.1.4": "Learn how dopamine and rewards drive the urge to spend and how retailers use this. Use that knowledge to reduce reward-based spending and feel better with your money.",
  "1.1.5": "Understand why waiting for something pays off and how it builds financial discipline. Practice delaying small rewards so you can aim for bigger goals.",
  "1.1.6": "Discover the hidden beliefs you have about money and where they come from. Start to question and update scripts that hold you back.",
  "1.1.7": "See how fear, stress, and excitement affect spending and saving. Learn to notice emotions before they drive money decisions.",
  "1.1.8": "Learn how first numbers (anchors) shape what you think is fair to pay. Use this to avoid overpaying and to set your own reference points.",
  "1.1.9": "Compare a scarcity mindset (never enough) with an abundance mindset (enough to grow). Shift your focus so you make choices from possibility, not fear.",
  "1.1.10": "Connect your spending to what you truly value so money supports your life. Align your budget with your values for more satisfaction and less guilt.",
  "1.1.11": "Set financial goals that are specific, realistic, and motivating. Break them into steps and track progress so you stay on course.",
  "1.1.12": "Learn which daily habits build wealth (saving, tracking, learning) and which drain it. Replace one bad habit with one good one and build from there.",

  "1.2.1": "Define income and the main ways people earn money. See how income fits into your overall financial picture.",
  "1.2.2": "Understand salary, wages, and how paychecks work in practice. Learn common terms like gross pay and pay period.",
  "1.2.3": "Learn the difference between gross income (before deductions) and net income (take-home). Use this to budget on real available money.",
  "1.2.4": "Read a payslip from top to bottom and understand each line. Know what’s taken out and why so you can spot errors.",
  "1.2.5": "Explore side hustles and gig work as ways to add income. Weigh flexibility and extra cash against time and stability.",
  "1.2.6": "Get the basics of freelancing: finding work, setting rates, and getting paid. Understand taxes and record-keeping for the self-employed.",
  "1.2.7": "Compare active income (trading time for money) with passive income (earnings with less ongoing effort). See where each fits in a long-term plan.",
  "1.2.8": "Learn how to ask for a raise and negotiate pay with confidence. Prepare with research and practice so you can have the conversation.",
  "1.2.9": "Understand common benefits and perks (health, retirement, PTO) and what they’re worth. Factor them into total compensation when comparing jobs.",
  "1.2.10": "See how income is taxed and what affects your tax bill. Get a clear picture of deductions and withholding so you’re not surprised at tax time.",
  "1.2.11": "Manage income that varies month to month or year to year. Learn to smooth spending and save in good months for lean ones.",
  "1.2.12": "Build toward multiple sources of income for security and growth. Start with one extra stream and add over time.",

  "1.3.1": "See why tracking money is the foundation of control and change. Learn how awareness alone often improves behavior.",
  "1.3.2": "Separate income from expenses and track both in a simple system. Use categories that match how you actually spend.",
  "1.3.3": "Define a budget as a plan for your money, not a punishment. Use it to direct cash toward what matters most.",
  "1.3.4": "Tell fixed costs (rent, insurance) from variable ones (food, fun). Use this to plan and to find room to save.",
  "1.3.5": "Understand cash flow: money in, money out, and timing. Avoid running short by matching outflows to when money arrives.",
  "1.3.6": "Apply the 50/30/20 rule: needs, wants, and savings. Adapt the percentages to your situation and goals.",
  "1.3.7": "Learn zero-based budgeting: assign every dollar a job. Get a clear plan and fewer “mystery” expenses.",
  "1.3.8": "Compare envelope, zero-based, and percentage-based budgeting. Choose one method and stick with it for a few months.",
  "1.3.9": "Use apps and tools to track spending and stay on budget. Pick one that fits your style and sync it to your habits.",
  "1.3.10": "Categorize spending so you see where money really goes. Use categories that help you make better choices.",
  "1.3.11": "Find spending leaks: small, repeated expenses that add up. Plug a few leaks and redirect that money to savings or debt.",
  "1.3.12": "Review your budget regularly and adjust when life or goals change. Make it a habit so your plan stays useful.",

  "2.1.1": "Learn what a bank is, what it does, and why people use one. See how banks keep your money safe and provide access and services.",
  "2.1.2": "Understand checking accounts: deposits, withdrawals, and everyday use. Choose an account with low fees and the features you need.",
  "2.1.3": "Use savings accounts to hold money you don’t need daily. Compare interest and access so you earn a bit while staying liquid.",
  "2.1.4": "Understand interest and APY and how they grow your savings. Shop for better rates to make your cash work harder.",
  "2.1.5": "Use debit cards safely: how they work, how they differ from credit, and how to avoid fees and fraud.",
  "2.1.6": "Use ATMs wisely and avoid unnecessary withdrawal fees. Know when to use your bank’s network and when to skip the machine.",
  "2.1.7": "Explore digital payments and e-wallets and when they’re useful. Use them safely and understand how they link to your accounts.",
  "2.1.8": "Set up direct deposit and understand how payroll works. Get your pay faster and avoid check-cashing fees.",
  "2.1.9": "Move money between accounts and pay bills on time. Use transfers and scheduled payments to stay in control.",
  "2.1.10": "Avoid overdrafts and understand bank fees so you keep more of your money. Opt out of overdraft “protection” if it just adds cost.",
  "2.1.11": "Bank online and on your phone safely and efficiently. Use strong passwords and only on secure networks.",
  "2.1.12": "Protect your accounts from fraud and identity theft. Learn red flags and simple habits that keep you safe.",
  "2.1.13": "Compare credit unions and banks and choose the right home for your accounts. Often credit unions offer better rates and fewer fees.",
  "2.1.14": "Understand deposit protection (e.g. FDIC/NCUA) and what’s covered. Keep your money in insured institutions.",
  "2.1.15": "Open your first (or next) account step by step. Bring the right ID and know what to ask about fees and features.",
  "2.1.16": "Read a bank statement and verify transactions. Use it to track spending and catch errors or fraud.",

  "2.2.1": "Define debt: what it is, how you borrow, and what you owe. See how debt can help or hurt depending on use and cost.",
  "2.2.2": "Tell good debt (productive, lower rate) from bad debt (high cost, no lasting value). Use this to decide when to borrow.",
  "2.2.3": "Understand credit: how it works, who extends it, and how it’s reported. Build a clear picture before you take on obligations.",
  "2.2.4": "Learn how credit scores are calculated and what typically helps or hurts them. Know your score and what to improve.",
  "2.2.5": "See how lenders use credit scores for loans, cards, and even housing. Use this to prioritize building and protecting your score.",
  "2.2.6": "Read and use your credit reports from major bureaus. Dispute errors and monitor for identity theft.",
  "2.2.7": "Understand how credit cards work: billing, minimums, and interest. Use them as a tool, not a trap.",
  "2.2.8": "Learn APR and how interest on cards is calculated. Pay in full when possible to avoid costly interest.",
  "2.2.9": "See why paying only the minimum keeps you in debt for years. Plan to pay more than the minimum or pay in full.",
  "2.2.10": "Understand how interest compounds on debt and makes it grow. Use this to motivate faster payoff and avoid new high-interest debt.",
  "2.2.11": "Create a plan to pay off credit card debt and stick to it. Choose a method (snowball or avalanche) that fits your psychology.",
  "2.2.12": "Understand consumer and installment loans and their true cost. Compare options before you sign.",
  "2.2.13": "Calculate the total cost of a loan including fees and interest. Use it to compare offers and decide if you can afford it.",
  "2.2.14": "Navigate student loans: types, repayment, and options. Make a plan that fits your income and goals.",
  "2.2.15": "Understand car loans and how to get a fair deal. Avoid long terms and high rates that leave you underwater.",
  "2.2.16": "Learn mortgage basics: how they work, key terms, and what affects your payment. Prepare before you shop for a home.",
  "2.2.17": "Spot predatory lending and high-cost products that trap borrowers. Know your alternatives and when to walk away.",
  "2.2.18": "Compare the debt snowball and debt avalanche methods. Pick one and use it to pay off debt faster.",
  "2.2.19": "Know when using credit makes sense and when it doesn’t. Use credit wisely for convenience and building history, not for lifestyle.",
  "2.2.20": "Build credit from scratch with secured cards, small loans, or authorized-user status. Establish a positive history over time.",
  "2.2.21": "Understand the risks of cosigning and guaranteeing someone else’s debt. Only do it if you can afford to pay the full amount.",
  "2.2.22": "See how debt spirals start and how to stop them early. Get help and change habits before the spiral grows.",
  "2.2.23": "Understand collections and default: what happens and what you can do. Know your rights and options to resolve or manage debt.",
  "2.2.24": "Learn the basics of bankruptcy: when it’s an option and what it does and doesn’t do. Consider it as a last resort with professional advice.",
  "2.2.25": "Build habits and systems to stay out of debt for the long term. Use budgets, emergency savings, and clear rules for borrowing.",

  "2.3.1": "Define inflation and how it erodes purchasing power over time. Use this to plan for rising costs and real returns.",
  "2.3.2": "See how prices change over time and why the same amount of money buys less. Use history to set realistic expectations.",
  "2.3.3": "Understand purchasing power and how inflation affects what you can buy. Plan savings and goals in real terms.",
  "2.3.4": "Learn the time value of money: why a dollar today is worth more than a dollar later. Apply it to saving and investing decisions.",
  "2.3.5": "See how compound growth grows your money over long periods. Start early so time works for you.",
  "2.3.6": "Understand why starting to save and invest early matters so much. Use examples to see the power of time in the market.",
  "2.3.7": "Distinguish real returns (after inflation) from nominal returns. Judge performance and goals in real terms.",
  "2.3.8": "See how inflation and wages interact over time. Use this to plan career and income growth.",
  "2.3.9": "Plan for rising costs in your budget and long-term goals. Build inflation into your assumptions.",
  "2.3.10": "Adopt long-term financial thinking for saving, investing, and debt. Balance today’s needs with tomorrow’s security.",

  "2.4.1": "Define an emergency fund and why it’s the first savings goal. It keeps you from going into debt when life hits.",
  "2.4.2": "Decide how much to save in your emergency fund (e.g. 3–6 months of expenses). Adjust for job stability and dependents.",
  "2.4.3": "Choose where to keep your emergency fund: accessible and safe. Use a separate savings account so you don’t spend it.",
  "2.4.4": "Build an emergency fund even on a tight budget. Start small and automate so it grows over time.",
  "2.4.5": "Know when and how to use your emergency fund—and when to leave it alone. Replenish it after you use it.",

  "3.1.1": "Define investing and how it differs from saving. See how it can grow wealth over the long term.",
  "3.1.2": "Compare investing and saving: purpose, risk, and time horizon. Use both in a balanced plan.",
  "3.1.3": "Understand the relationship between risk and return. Accept the right level of risk for your goals and timeline.",
  "3.1.4": "Learn stock basics: what they are, how they can grow in value, and key risks. Build a foundation before buying.",
  "3.1.5": "Learn bond basics: how they work, interest, and role in a portfolio. Use them for income and stability.",
  "3.1.6": "Understand mutual funds and ETFs and how they give you diversification. Choose low-cost funds that match your strategy.",
  "3.1.7": "Learn why index funds are a simple, low-cost way to invest in the market. Consider them as a core holding.",
  "3.1.8": "Use diversification to spread risk across assets and reduce volatility. Don’t put all your money in one place.",
  "3.1.9": "Apply asset allocation to split money among stocks, bonds, and other assets. Align it with your age and goals.",
  "3.1.10": "Use tax-advantaged retirement accounts (e.g. 401(k), IRA) to save for the future. Get employer match if available.",
  "3.1.11": "Understand state pensions and retirement systems where you live. Factor them into your retirement plan.",
  "3.1.12": "Learn how brokerages work and how to choose one. Consider fees, tools, and what you need to invest.",
  "3.1.13": "See how investment fees and costs reduce returns over time. Prefer low-cost options when possible.",
  "3.1.14": "Use dollar-cost averaging to invest regularly and smooth out market timing. Build discipline and reduce emotion.",
  "3.1.15": "Rebalance your portfolio periodically to keep your target allocation. Sell high and buy low in a disciplined way.",
  "3.1.16": "Match your investments to your time horizon: longer horizons can take more risk. Avoid taking big risks with money you need soon.",
  "3.1.17": "Understand market volatility and why prices swing. Stay calm and stick to your plan instead of reacting to short-term moves.",
  "3.1.18": "Learn what bull and bear markets are and how to behave in each. Avoid panic selling and euphoric buying.",
  "3.1.19": "Understand dividends and capital gains and how they’re taxed. Use them in your income and tax planning.",
  "3.1.20": "Take the steps to make your first investment in a low-cost, diversified way. Start small and learn as you go.",

  "3.2.1": "See how global stock markets work and how they’re connected. Understand why geography and regulation matter.",
  "3.2.2": "Learn options and considerations for investing in US markets from outside the US. Know tax and regulatory basics.",
  "3.2.3": "Understand currency risk and exchange rates when you invest across borders. See how they affect returns.",
  "3.2.4": "Compare domestic and international investing and how to balance them. Diversify across regions for long-term growth.",
  "3.2.5": "Understand emerging markets: higher growth and higher risk. Consider a small allocation if it fits your plan.",
  "3.2.6": "Learn sector investing and how to use sectors for diversification or tilts. Don’t concentrate too much in one sector.",
  "3.2.7": "Explore ESG and ethical investing and how to align investments with values. Weigh impact and returns.",
  "3.2.8": "Compare passive and active strategies and when each might make sense. Most people are better off with low-cost passive core.",
  "3.2.9": "Know when to sell an investment: rebalancing, goal reached, or thesis broken. Avoid selling just on short-term noise.",
  "3.2.10": "Reinvest returns to benefit from compounding. Use dividends and interest to buy more shares when that fits your plan.",

  "3.3.1": "Define assets and how they fit into your balance sheet. Know what you own and what it’s worth.",
  "3.3.2": "Calculate and track net worth as a snapshot of your financial health. Use it to measure progress over time.",
  "3.3.3": "Build equity in a home, business, or investments. Understand how ownership grows in value over time.",
  "3.3.4": "Learn real estate basics: types, how value can grow, and key risks. See how it can fit in a long-term plan.",
  "3.3.5": "Compare renting and owning: costs, flexibility, and building equity. Choose based on your situation and goals.",
  "3.3.6": "Distinguish liquid assets (easy to sell) from illiquid ones (harder to sell). Balance both for access and return.",
  "3.3.7": "Tell appreciating assets from depreciating ones and how each affects wealth. Prefer assets that hold or grow value.",
  "3.3.8": "Understand income-producing assets and how they can generate cash flow. Use them for income and diversification.",
  "3.3.9": "Separate passive income reality from myth and get-rich-quick claims. Build real income streams with patience.",
  "3.3.10": "Learn business ownership basics: equity, risk, and potential returns. See how it differs from being an employee.",
  "3.3.11": "Explore entrepreneurship as a path to income and wealth. Weigh the tradeoffs and what you need to succeed.",
  "3.3.12": "Distinguish profit from cash flow in a business or side project. Manage both to stay solvent and grow.",
  "3.3.13": "Understand margins and how much you keep from each sale or project. Improve margins to grow income.",
  "3.3.14": "Plan to scale income over time through skills, assets, or business. Set milestones and invest in yourself.",
  "3.3.15": "Use opportunity cost to compare choices: what you give up when you choose one option. Apply it to time and money.",
  "3.3.16": "Think in terms of a portfolio: multiple income sources and assets. Diversify so one setback doesn’t ruin you.",
  "3.3.17": "Define financial independence and what it means for you. Plan savings and spending so you can reach it.",
  "3.3.18": "Learn the FIRE concept (Financial Independence, Retire Early) and how people pursue it. Adapt the principles to your goals.",
  "3.3.19": "Use insurance to protect wealth from large, unexpected losses. Cover the big risks; don’t over-insure the small ones.",
  "3.3.20": "Understand estate planning basics: wills, beneficiaries, and why they matter. Ensure your wishes are clear and updated.",
  "3.3.21": "Think about generational wealth and how to pass on money and values. Use legal tools and family communication.",
  "3.3.22": "Design wealth and lifestyle together so money supports the life you want. Avoid lifestyle creep that keeps you running in place.",
  "3.3.23": "Build a 5-year wealth plan: goals, savings, debt, and investments. Review it yearly and adjust.",

  "4.1.1": "Define risk in a financial context and how it relates to uncertainty. Accept that all choices involve some risk.",
  "4.1.2": "Learn probability basics so you can weigh odds in money decisions. Use simple math to compare options.",
  "4.1.3": "Use expected value to compare choices when outcomes are uncertain. Don’t confuse possible outcomes with likely ones.",
  "4.1.4": "Assess your risk tolerance and how much volatility you can handle. Match investments and decisions to your comfort.",
  "4.1.5": "Understand insurance basics: what it covers, deductibles, and when it’s worth it. Protect against large losses first.",
  "4.1.6": "Learn health and disability insurance and why they matter. Get coverage that fits your situation.",
  "4.1.7": "Understand odds in gambling and other risky situations. See how the house edge works and why most gamblers lose.",
  "4.1.8": "Apply gambling math to see why games are stacked against players. Use this to avoid betting money you can’t afford to lose.",
  "4.1.9": "Distinguish gambling from investing: edge, time horizon, and purpose. Invest; don’t gamble with your future.",
  "4.1.10": "Tell speculation (betting on price moves) from investing (owning for the long term). Prefer investing for wealth building.",
  "4.1.11": "See how emotions drive bad investment decisions. Use rules and discipline to stay on plan.",
  "4.1.12": "Understand black swan events: rare, big shocks and how they affect markets. Don’t overreact; keep a long-term plan.",
  "4.1.13": "Manage downside risk with diversification, insurance, and sensible allocation. Protect what you’ve built.",

  "4.2.1": "Understand payday loans and why they’re almost always a bad idea. Find safer alternatives for short-term cash needs.",
  "4.2.2": "Spot high-interest traps in loans, cards, and buy-now-pay-later. Calculate true cost before you borrow.",
  "4.2.3": "See how buy now, pay later can lead to overspending and hidden cost. Use it sparingly or not at all.",
  "4.2.4": "Catch subscription creep: recurring charges that add up. Audit and cancel what you don’t use.",
  "4.2.5": "Understand lifestyle inflation and how raises get spent instead of saved. Decide in advance how much of new income to keep.",
  "4.2.6": "Recognize FOMO spending and how it pushes you to buy. Pause and ask if you really need it.",
  "4.2.7": "Understand market bubbles and crashes and how to avoid panic. Stay diversified and don’t chase hype.",
  "4.2.8": "Learn the risks of leverage and margin: bigger gains and much bigger losses. Avoid them until you’re experienced.",
  "4.2.9": "Spot pyramid and Ponzi schemes and how they collapse. If it promises easy, high returns, be very skeptical.",
  "4.2.10": "Recognize investment scams and too-good-to-be-true offers. Protect your money by verifying and saying no.",
  "4.2.11": "Protect yourself from phishing and identity theft. Use strong passwords and never share sensitive data by email or phone.",
  "4.2.12": "Resist pressure tactics and fake urgency in sales and scams. Take time and check facts before committing.",
  "4.2.13": "Find hidden fees and read the fine print before you sign. Compare total cost, not just headline rates.",
  "4.2.14": "See how social media creates spending pressure and comparison. Limit exposure and set your own standards.",
  "4.2.15": "Understand influencer marketing and how it targets your wallet. Separate entertainment from advice and ads.",
  "4.2.16": "Protect your financial data and accounts with good habits and tools. Lock down logins and monitor for fraud.",
  "4.2.17": "Build a scam detection filter: red flags and checks before you send money or invest. When in doubt, don’t.",

  "4.3.1": "Understand why we pay taxes and what they fund. See your role as a taxpayer in society.",
  "4.3.2": "Learn income tax basics: what’s taxed, how it’s calculated, and when you pay. Get a clear picture of your liability.",
  "4.3.3": "Understand tax brackets and marginal rates so you’re not surprised. Know the difference between marginal and effective rate.",
  "4.3.4": "Use deductions and credits to lower your tax bill legally. Know which apply to you and keep records.",
  "4.3.5": "File a tax return on time and correctly. Use software or a pro if needed; avoid shortcuts that create problems.",
  "4.3.6": "Compare employment and self-employment taxes and what you owe in each case. Set aside money if you’re self-employed.",
  "4.3.7": "Understand VAT and consumption taxes and how they affect prices and saving. Factor them into budgets and comparisons.",
  "4.3.8": "Learn how capital gains tax works on investments. Use holding periods and accounts to manage the bill.",
  "4.3.9": "Use tax-advantaged accounts and planning to keep more of what you earn. Align strategy with your goals and rules.",
  "4.3.10": "Connect taxes to public goods and civic responsibility. Participate in the system and plan for your obligations.",

  "5.1.1": "Tell your money story: where you started and what you’ve learned. Use it to set the direction for your next chapter.",
  "5.1.2": "Revisit your goals and align them with your current life and values. Update targets and timelines so they still motivate you.",
  "5.1.3": "Build financial systems: habits, accounts, and routines that run without constant willpower. Automate and simplify.",
  "5.1.4": "Lock in your emergency fund plan: amount, account, and refill rule. Make it non-negotiable.",
  "5.1.5": "Create a debt-free strategy: payoff order, extra payments, and a date. Stick to it until you’re free.",
  "5.1.6": "Define your investment strategy: allocation, accounts, and contributions. Write it down and follow it.",
  "5.1.7": "Plan for income growth: skills, side income, and career moves. Set milestones for the next few years.",
  "5.1.8": "Complete your risk and protection plan: insurance and emergency fund. Cover the big risks first.",
  "5.1.9": "Finalize your scam protection plan: how you’ll verify and say no. Share it with family so they’re protected too.",
  "5.1.10": "Articulate your long-term vision: what you want money to do for you in 10–20 years. Use it to guide decisions.",
  "5.1.11": "Prepare to teach others: family, friends, or community. Share what you’ve learned in simple, practical ways.",
  "5.1.12": "Reflect on community and money: giving, support, and values. Decide how you want to contribute.",
  "5.1.13": "State your wealth philosophy: what wealth means to you and how you’ll use it. Live in line with it.",
  "5.1.14": "Assemble your complete financial blueprint: goals, systems, and next actions. Keep it in one place and review it yearly.",
  "5.1.15": "Celebrate graduating ArcWealth and commit to lifelong learning. You have the foundation; keep building.",
};
